Mission2/Models/GradeCalcModel.cs
using System;
//Added these "usings" manually
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission2.Models
{
    public class GradeCalcModel
    {
        //[Required]
        [Range(0,100, ErrorMessage = "Assignments grade must be between 0 to 100")]
        public int Assignments { get; set; }

        [Range(0, 100, ErrorMessage = "Group Projects grade must be between 0 to 100")]
        public int GroupProjects { get; set; }

        [Range(0, 100, ErrorMessage = "Quizzes grade must be between 0 to 100")]
        public int Quizzes { get; set; }

        [Range(0, 100, ErrorMessage = "Exams grade must be between 0 to 100")]
        public int Exams { get; set; }

        [Range(0, 100, ErrorMessage = "INTEX grade must be between 0 to 100")]
        public int INTEX { get; set; }
    }
}

Mission2/Controllers/BlahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission2.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mission2.Controllers
{
    public class BlahController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("GradeCalcModel")]
        public IActionResult GradeCalc ()
        {
            return View();
        }

        [HttpPost("GradeCalcModel")]
        public IActionResult GradeCalc (GradeCalcModel model)
        {
            return View();
        }
    }
}

Mission2/Views/Blah/GradeCalc.cshtml
@*John Berthelsen*@
@*Grade Calculator HTML*@
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}

@model GradeCalcModel;
<!--Grade Calculator Form-->
<div style="align-content: center; align-items:center; align-self:center;">
    <form method="post" style="text-align: center; align-content: center; align-items:center; display: flex; flex-direction: column; justify-content: center; outline: 5px solid red; width: 350px;">
        <h2>Grade Calculator</h2>
        <label>Assignments %</label><br />
        <input id="AssignmentsPct" asp-for="Assignments" type="number"/><br /><br />
        <label>Group Project %</label><br />
        <input id="GroupProjectPct" asp-for="GroupProjects" type="number"/><br /><br />
        <label>Quizzes %</label><br />
        <input id="QuizzesPct" asp-for="Quizzes" type="number"/><br /><br />
        <label>Exams %</label><br />
        <input id="ExamsPct" asp-for="Exams" type="number"/><br /><br />
        <label>INTEX %</label><br />
        <input id="INTEXPct" asp-for="INTEX" type="number"/><br /><br />
        <button id="btnCalc" type="submit" value="Calculate">Calculate</button>

        <div asp-validation-summary="All"></div>
    </form>
</div>
<br />

Mission2/Views/Blah/Index.cshtml
@*John Berthelsen*@
@*Home Page HTML*@
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Mission #3";
}

<!--Header-->
<h1>John Berthelsen</h1>

<!--Fun Image-->
<img src="img/JohnScuba.jpg"
        width="350"
        height="450"
        align-items="center" />
<br />

<!--IS 413 Expectations-->
<form style="outline: 5px solid red; width: 600px; padding-top: 30px; padding-right: 30px; padding-bottom: 15px; padding-left: 30px; align-content: center; align-items: center; display: flex; flex-direction: column; justify-content: center; outline: 5px solid red; margin-bottom: 25px; margin-left: auto; margin-right: auto;">
    <p>
        Upon completion of the IS 413 course, I hope I will have gained a greater understanding of ASP.NET
        and have become more proficient in C#. As I study Enterprise Application Development, I hope to learn
        the basics of the programs and tools used by developers in business. I look forward to working with
        my group on future projects and what I can learn from them. Most of all, I look forward to applying
        what I learn to my own business in the near future.
    </p>

    <!--Interesting Jobs-->
    <p>The 3 jobs I am most interested in upon graduating are:</p>
    <ul>
        <li>Pilot</li>
        <li>Skydiver</li>
        <li>Web Developer</li>
    </ul>
</form>

Mission2/Views/Shared/_Layout.cshtml
@*John Berthelsen*@
@*Master HTML page*@
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <!--Webpage Title-->
    <title>@ViewData["Title"]</title>
    <!--Bootstrap CSS-->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!--My Custom CSS-->
    <link href="~/css/default.css" rel="stylesheet" />
    <!--Custom Tab Icon-->
    <link href="~/img/scubaflag.png" rel="icon" />

</head>

<body>

    <nav>
        <a asp-controller="Blah" asp-action="Index" style="color:white; padding-left:200px; padding-top:50px; font-size:x-large;">Home</a>&nbsp;&nbsp;
        <a asp-controller="Blah" asp-action="GradeCalc" style="color: white; padding-top: 50px; font-size: x-large;">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    @*<footer style="text-align:center; align-items:center; align-content:center; color:darkcyan;">&copy Copyright 2022</footer>*@

    <!--JavaScript-->
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
    <script src="~/js/GradeCalc.js"></script>

</body>

</html>